apiVersion: v1
kind: Service
metadata:
    name: "aksyanademo-2233"
    labels:
        app: "aksyanademo-2233"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksyanademo-2233"