on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemoyana.azurecr.io
        username: ${{ secrets.acr_acrdemoyana_username }}
        password: ${{ secrets.acr_acrdemoyana_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemoyana.azurecr.io/aksyanademo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemoyana.azurecr.io/aksyanademo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksyanademo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-yana-demoae47 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-yana-demoae47`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-yana-demoae47
        container-registry-url: acrdemoyana.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemoyana_username }}
        container-registry-password: ${{ secrets.acr_acrdemoyana_password }}
        secret-name: aksyanademodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-yana-demoae47
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          acrdemoyana.azurecr.io/aksyanademo:${{ github.sha }}
        imagepullsecrets: |
          aksyanademodockerauth
